"""Places berlin52's points on Berlin, for orientation only, and writes Berlin's districts in the
points' coordinates as a small JS module: components/projects/genoxide/player/plots/berlin.js.

Run from the repository's root: python site/scripts/berlin_districts.py (needs numpy and shapely).
It downloads the district boundaries from Geoportal Berlin's WFS (ALKIS Berlin Bezirke, under the
Datenlizenz Deutschland - Zero - Version 2.0).

TSPLIB gives no real positions, so the placement is a choice: the scale and shift that keep every
point well inside Berlin, with the dense cluster (the likely centre) near Mitte, north up and the
points' y growing northward.
"""
import json, math, urllib.request
import numpy as np
from shapely.geometry import shape, Point, Polygon, MultiPolygon
from shapely.ops import unary_union, transform

REPO = ""  # the repository's root, the working directory
WFS = (
    "https://gdi.berlin.de/services/wfs/alkis_bezirke?service=WFS&version=2.0.0&request=GetFeature"
    "&typeNames=alkis_bezirke:bezirksgrenzen&outputFormat=application/json&srsName=EPSG:4326"
)

# the points, as the trace has them
trace = json.load(open(REPO + "examples/tsp_berlin52/trace.json", encoding="utf-8"))
P = np.array(trace["problem"]["points"], dtype=float)

# kilometres east and north of a reference point, equirectangular at Berlin's latitude
LON0, LAT0 = 13.40, 52.52
KX = 111.320 * math.cos(math.radians(LAT0))
KY = 110.574
def to_km(lon, lat, z=None):
    return ((np.asarray(lon) - LON0) * KX, (np.asarray(lat) - LAT0) * KY)

with urllib.request.urlopen(WFS, timeout=60) as response:
    g = json.load(response)
districts = [(f["properties"]["namgem"], transform(to_km, shape(f["geometry"]))) for f in g["features"]]
berlin = unary_union([d for _, d in districts])

# the dense cluster, the likely centre, and where to put it: Mitte (Unter den Linden)
cluster = (P[:, 0] > 650) & (P[:, 0] < 900) & (P[:, 1] > 560) & (P[:, 1] < 710)
centre = P[cluster].mean(axis=0)
mitte = np.array(to_km(13.39, 52.517))

from shapely import prepared
inside_berlin = prepared.prep(berlin)
# from the largest scale down (the larger, the more of the map the tour fills), the first that
# keeps every location at least 1 km inside Berlin with the cluster within 2 km of Mitte; at that
# scale, the widest margin
best = None
for s in np.arange(0.024, 0.0119, -0.0005):          # km per TSPLIB unit
    for dx in np.linspace(-2, 2, 17):
        for dy in np.linspace(-2, 2, 17):
            if math.hypot(dx, dy) > 2.0:
                continue
            shift = mitte + np.array([dx, dy]) - centre * s
            pts = P * s + shift
            if not all(inside_berlin.contains(Point(p)) for p in pts):
                continue
            margin = min(berlin.boundary.distance(Point(p)) for p in pts)
            if margin >= 1.0 and (best is None or margin > best[3]):
                best = (None, s, shift, margin, dx, dy)
    if best is not None:
        break
score, s, shift, margin, dx, dy = best
print(f"scale {s*1000:.1f} m per unit, cluster {math.hypot(dx, dy):.1f} km from Mitte, margin {margin:.2f} km")

# the districts in TSPLIB coordinates, simplified
def to_points(x, y, z=None):
    return ((np.asarray(x) - shift[0]) / s, (np.asarray(y) - shift[1]) / s)
out = []
for name, geom in districts:
    geom = transform(to_points, geom).simplify(4.0, preserve_topology=True)
    polys = geom.geoms if isinstance(geom, MultiPolygon) else [geom]
    rings = [[[round(x), round(y)] for x, y in poly.exterior.coords[:-1]] for poly in polys if poly.area > 50]
    out.append((name, rings))
outline = transform(to_points, berlin).simplify(4.0, preserve_topology=True)
print("vertices:", sum(len(r) for _, rs in out for r in rs))

def js_rings(rings):
    return "[" + ",".join("[" + ",".join(f"[{x},{y}]" for x, y in r) + "]" for r in rings) + "]"

module = f'''// Berlin's twelve districts, in the coordinates of TSPLIB's berlin52, for the example page's tour
// plot. TSPLIB gives no real positions for its 52 locations ("52 locations in Berlin
// (Groetschel)"), so the placement is a choice, for orientation only: every location inside
// Berlin, the dense cluster, the likely centre, near Mitte, north up, {s * 1000:.1f} m per unit.
//
// Source: Geoportal Berlin, ALKIS Berlin Bezirke (district boundaries), Senatsverwaltung für
// Stadtentwicklung, Bauen und Wohnen, under the Datenlizenz Deutschland – Zero – Version 2.0
// (https://www.govdata.de/dl-de/zero-2-0): any use, without conditions. Simplified to about 4
// units (about {4 * s * 1000:.0f} m). Generated by site/scripts/berlin_districts.py: don't edit by hand.

/** @type {{{{ name: string, rings: number[][][] }}[]}} */
export const BERLIN_DISTRICTS = [
{chr(10).join(f'  {{ name: {json.dumps(name, ensure_ascii=False)}, rings: {js_rings(rings)} }},' for name, rings in out)}
];
'''
path = REPO + "site/components/projects/genoxide/player/plots/berlin.js"
open(path, "w", encoding="utf-8", newline="\n").write(module)
print("wrote", len(module.encode()), "bytes")
