from collections.abc import Callable
from typing import Any

import numpy as np

__version__: str

def run(
    config: str,
    fitness: Callable[[Any], Any],
    batch: bool = False,
    parallel: bool = False,
    on_generation: Callable[..., bool] | None = None,
    problem: str | None = None,
    control: Callable[..., None] | None = None,
) -> dict[str, Any]: ...

class Running:
    """The running algorithm, for a control: valid during the control's call only."""

    def get(self, name: str) -> str: ...
    def set(self, name: str, value: str) -> None: ...
    def reevaluate(self) -> None: ...

class Snapshot:
    """A population (or a front) after a generation, for a progress object: its arrays are made
    when read."""

    def genomes(self) -> np.ndarray | None: ...
    def values(self) -> np.ndarray: ...
    def violations(self) -> np.ndarray: ...

def das_dennis(objectives: int, divisions: int) -> np.ndarray: ...
def problem_info(problem: str) -> dict[str, Any]: ...
def evaluate(problem: str, genomes: np.ndarray) -> Any: ...
def constraints(problem: str, genome: np.ndarray) -> np.ndarray: ...
def optimal_front(problem: str, points: int) -> np.ndarray | None: ...
def design(problem: str, genome: np.ndarray) -> np.ndarray: ...
def problem_names() -> list[str]: ...
def multi_problem_names(objectives: int) -> list[str]: ...
def indicator(
    kind: str, front: np.ndarray, reference: np.ndarray, objectives: list[str]
) -> float: ...
