import os
from collections.abc import Callable
from typing import Any

import numpy as np

__version__: str

def run(
    config: str,
    fitness: Callable[[Any], Any],
    batch: bool = False,
    parallel: bool = False,
    on_generation: Callable[..., bool] | None = None,
    problem: str | None = None,
    control: Callable[..., None] | None = None,
    checkpoint: str | os.PathLike[str] | None = None,
    checkpoint_every: int | None = None,
    resume: str | os.PathLike[str] | None = None,
) -> dict[str, Any]: ...

class Running:
    """The running algorithm, for a control: valid during the control's call only."""

    def get(self, name: str) -> str: ...
    def set(self, name: str, value: str) -> None: ...
    def reevaluate(self) -> None: ...

class Snapshot:
    """A population (or a front) after a generation, for a progress object: its arrays are made
    when read."""

    def genomes(self) -> np.ndarray | None: ...
    def values(self) -> np.ndarray: ...
    def violations(self) -> np.ndarray: ...

def das_dennis(objectives: int, divisions: int) -> np.ndarray: ...
def problem_info(problem: str) -> dict[str, Any]: ...
def evaluate(problem: str, genomes: np.ndarray) -> Any: ...
def constraints(problem: str, genome: np.ndarray) -> np.ndarray: ...
def optimal_front(problem: str, points: int) -> np.ndarray | None: ...
def design(problem: str, genome: np.ndarray) -> np.ndarray: ...
def problem_names() -> list[str]: ...
def multi_problem_names(objectives: int) -> list[str]: ...
def indicator(
    kind: str, front: np.ndarray, reference: np.ndarray, objectives: list[str]
) -> float: ...

class Network:
    """A network of ``gx.nn``, from its description."""

    def __init__(self, description: str) -> None: ...
    @property
    def parameters(self) -> int: ...
    @property
    def inputs(self) -> int: ...
    @property
    def outputs(self) -> int: ...
    def forward(self, weights: np.ndarray, inputs: np.ndarray) -> np.ndarray: ...
    def policy(self, weights: np.ndarray) -> Policy: ...

class Policy:
    """A network with its weights, a policy of the control tasks that runs in Rust."""

    @property
    def inputs(self) -> int: ...
    @property
    def outputs(self) -> int: ...

class Task:
    """A control task of ``gx.problems.control``, from its description."""

    def __init__(self, description: str) -> None: ...
    @property
    def observations(self) -> int: ...
    def run(self, policy: Any, steps: int) -> int: ...
    def solved(self, policy: Any) -> bool: ...
    def damping_fitness(self, policy: Any) -> float: ...
    def generalization(self, policy: Any) -> int: ...

SUCCESS_STEPS: int
DAMPING_STEPS: int
GENERALIZATION_THRESHOLD: int

def balance_evaluate(description: str, genomes: np.ndarray) -> np.ndarray: ...
def portable_math(function: str, a: np.ndarray, b: np.ndarray | None = None) -> np.ndarray: ...
def random_real(bounds: list[tuple[float, float]], seed: int) -> np.ndarray: ...
